"""
Automatic Plugin Installer for GALION.studio Server
===================================================

This script automatically downloads and installs essential server plugins:
- WorldEdit - Powerful building tool
- EssentialsX - Core commands and features
- LuckPerms - Advanced permissions system
- Vault - Economy API
- CoreProtect - Logging and rollback
- Citizens - NPC system
- GriefPrevention - Land protection
- Spark - Performance profiler

Author: galion.studio (Maciej Grajczyk)
"""

import os
import requests
from pathlib import Path
import json

# Plugin download URLs (using direct links)
# Note: Some plugins need manual download if URLs change
PLUGINS = {
    "WorldEdit": {
        "url": "https://mediafilez.forgecdn.net/files/5707/596/worldedit-bukkit-7.3.8.jar",
        "description": "In-game world editor for creative building",
        "essential": True
    },
    "EssentialsX": {
        "url": "https://github.com/EssentialsX/Essentials/releases/download/2.21.0-dev%2B109-4e2e1cd/EssentialsX-2.21.0-dev+109-4e2e1cd.jar",
        "description": "Essential commands, teleportation, economy, and more",
        "essential": True
    },
    "LuckPerms": {
        "url": "https://download.luckperms.net/1564/bukkit/loader/LuckPerms-Bukkit-5.4.141.jar",
        "description": "Advanced permissions management system",
        "essential": True
    },
    "Vault": {
        "url": "https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar",
        "description": "Economy and permission API for plugins",
        "essential": True
    },
    "CoreProtect": {
        "url": "https://github.com/PlayPro/CoreProtect/releases/download/22.4/CoreProtect-22.4.jar",
        "description": "Block logging and rollback tool",
        "essential": True
    },
    "GriefPrevention": {
        "url": "https://github.com/TechFortress/GriefPrevention/releases/download/16.18.4/GriefPrevention-16.18.4.jar",
        "description": "Land claim and protection system",
        "essential": True
    }
}

# Server plugins directory
PLUGINS_DIR = Path("worlds/hub/plugins")

def download_file(url: str, destination: Path, plugin_name: str) -> bool:
    """
    Download a file from URL to destination.
    
    Args:
        url: Download URL
        destination: Destination file path
        plugin_name: Name of the plugin (for logging)
        
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        print(f"  [>>] Downloading {plugin_name}...")
        
        # Set headers to mimic a browser
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        
        # Download with streaming to handle large files
        response = requests.get(url, headers=headers, stream=True, timeout=30, allow_redirects=True)
        response.raise_for_status()
        
        # Save to file
        with open(destination, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        
        # Verify file was created and has content
        if destination.exists() and destination.stat().st_size > 0:
            size_mb = destination.stat().st_size / (1024 * 1024)
            print(f"  [OK] {plugin_name} downloaded successfully ({size_mb:.2f} MB)")
            return True
        else:
            print(f"  [FAIL] {plugin_name} download failed (empty file)")
            return False
            
    except Exception as e:
        print(f"  [FAIL] Error downloading {plugin_name}: {e}")
        return False

def create_plugin_configs():
    """
    Create basic configuration files for plugins.
    """
    print("\n[3/3] Creating plugin configurations...")
    
    # Create LuckPerms config directory
    luckperms_dir = PLUGINS_DIR / "LuckPerms"
    luckperms_dir.mkdir(exist_ok=True)
    
    # Create WorldEdit config
    worldedit_config = """
# WorldEdit Configuration
# Generated by GALION.studio Auto-Setup

limits:
  max-blocks-changed:
    default: 1000000
  max-radius: 1000
  max-super-pickaxe-size: 10

history:
  size: 15
  expiration: 10

wand-item: minecraft:wooden_axe
no-double-slash: false
"""
    
    worldedit_dir = PLUGINS_DIR / "WorldEdit"
    worldedit_dir.mkdir(exist_ok=True)
    with open(worldedit_dir / "config.yml", 'w') as f:
        f.write(worldedit_config)
    print("  [OK] WorldEdit config created")
    
    # Create EssentialsX config
    essentials_config = """
# EssentialsX Configuration
# Generated by GALION.studio Auto-Setup

# Server info
server-name: GALION.studio
server-motd: Welcome to GALION.studio!

# Spawn settings
newbies:
  spawn-on-join: true
  announce-format: '&dWelcome &6{PLAYER}&d to the server!'

# Teleportation
teleport-cooldown: 0
teleport-delay: 0
teleport-invulnerability: 4

# Home settings
max-homes: 5
"""
    
    essentials_dir = PLUGINS_DIR / "Essentials"
    essentials_dir.mkdir(exist_ok=True)
    with open(essentials_dir / "config.yml", 'w') as f:
        f.write(essentials_config)
    print("  [OK] EssentialsX config created (will generate full config on first run)")
    
    # Create GriefPrevention config note
    gp_dir = PLUGINS_DIR / "GriefPrevention"
    gp_dir.mkdir(exist_ok=True)
    print("  [OK] GriefPrevention will generate config on first run")
    
    print("\n[OK] Basic configurations created!")

def install_plugins():
    """
    Main function to install all plugins.
    """
    print("="*70)
    print("  GALION.STUDIO - AUTOMATIC PLUGIN INSTALLER")
    print("="*70)
    print()
    
    # Check if plugins directory exists
    if not PLUGINS_DIR.exists():
        print(f"Creating plugins directory: {PLUGINS_DIR}")
        PLUGINS_DIR.mkdir(parents=True, exist_ok=True)
    
    print(f"Installing plugins to: {PLUGINS_DIR}")
    print()
    
    # Display plugin list
    print("Plugins to install:")
    for name, info in PLUGINS.items():
        essential = "[ESSENTIAL]" if info["essential"] else "[Optional]"
        print(f"  {essential} - {name}: {info['description']}")
    print()
    
    # Download plugins
    print("[1/3] Downloading plugins...")
    print("-"*70)
    
    success_count = 0
    failed_plugins = []
    
    for plugin_name, plugin_info in PLUGINS.items():
        destination = PLUGINS_DIR / f"{plugin_name}.jar"
        
        # Skip if already exists
        if destination.exists():
            print(f"  [SKIP] {plugin_name} already exists, skipping...")
            success_count += 1
            continue
        
        # Download plugin
        success = download_file(plugin_info["url"], destination, plugin_name)
        
        if success:
            success_count += 1
        else:
            failed_plugins.append(plugin_name)
    
    print()
    print("-"*70)
    print(f"Downloaded: {success_count}/{len(PLUGINS)} plugins")
    
    if failed_plugins:
        print(f"Failed: {', '.join(failed_plugins)}")
    
    # Create configurations
    create_plugin_configs()
    
    # Summary
    print()
    print("="*70)
    print("  INSTALLATION COMPLETE!")
    print("="*70)
    print()
    print("INSTALLED PLUGINS:")
    print()
    
    for plugin_file in PLUGINS_DIR.glob("*.jar"):
        size_mb = plugin_file.stat().st_size / (1024 * 1024)
        print(f"  [OK] {plugin_file.stem} ({size_mb:.2f} MB)")
    
    print()
    print("NEXT STEPS:")
    print()
    print("  1. Start your server:")
    print("     START-LOCAL-SERVER.cmd   (for offline play)")
    print("     START-OFFICIAL-SERVER.cmd (for online with AI)")
    print()
    print("  2. Grant yourself admin permissions:")
    print("     /op YourUsername")
    print()
    print("  3. Essential commands:")
    print("     /help WorldEdit  - WorldEdit help")
    print("     /help            - All commands")
    print("     /plugins         - List installed plugins")
    print()
    print("  4. WorldEdit basics:")
    print("     //wand          - Get WorldEdit wand")
    print("     //set stone     - Fill selection with stone")
    print("     //undo          - Undo last action")
    print("     //copy          - Copy selection")
    print("     //paste         - Paste copied blocks")
    print()
    print("  5. EssentialsX commands:")
    print("     /spawn          - Teleport to spawn")
    print("     /home           - Teleport home")
    print("     /sethome        - Set home location")
    print("     /tpa [player]   - Request teleport to player")
    print()
    print("DOCUMENTATION:")
    print("   WorldEdit: https://worldedit.enginehub.org/")
    print("   EssentialsX: https://essentialsx.net/")
    print("   LuckPerms: https://luckperms.net/")
    print()
    print("="*70)

if __name__ == "__main__":
    try:
        install_plugins()
    except KeyboardInterrupt:
        print("\n\nInstallation cancelled by user.")
    except Exception as e:
        print(f"\n\n[ERROR] Error during installation: {e}")
        import traceback
        traceback.print_exc()

